import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

// PostHogProvider is now mounted inside (app)/layout.tsx so unauth'd
// routes (/login, /global-error, /auth/*) don't pay the JS cost or
// initialize analytics before there's a user to identify.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Display face — characterful contemporary grotesque for titles + marquee
// numbers. Pairs with Geist as the UI workhorse.
const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

// iOS launch screens — one per device class, matched by media query. The
// images are generated by scripts/generate-pwa-assets.mjs; keep this list in
// sync with SPLASH_DEVICES there.
const IPHONE_SPLASH = [
  { css: [375, 667], dpr: 2 }, // SE 2/3
  { css: [414, 896], dpr: 2 }, // XR / 11
  { css: [414, 896], dpr: 3 }, // XS Max / 11 Pro Max
  { css: [375, 812], dpr: 3 }, // X / XS / 11 Pro / 12-13 mini
  { css: [390, 844], dpr: 3 }, // 12 / 13 / 14
  { css: [393, 852], dpr: 3 }, // 14 Pro / 15 / 16
  { css: [402, 874], dpr: 3 }, // 16 Pro / 17
  { css: [428, 926], dpr: 3 }, // 12-13 Pro Max / 14 Plus
  { css: [430, 932], dpr: 3 }, // 14-15 Pro Max / 15-16 Plus
  { css: [440, 956], dpr: 3 }, // 16 Pro Max / 17 Pro Max
].map(({ css: [w, h], dpr }) => ({
  url: `/splash/splash-${w * dpr}x${h * dpr}.png`,
  media: `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)`,
}));

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Edge-to-edge in the installed app; safe-area padding lives in globals.css.
  viewportFit: "cover",
  themeColor: "#faf9f6",
};

export const metadata: Metadata = {
  title: "TexasTurf OS",
  description: "TexasTurf operations and command center",
  applicationName: "TexasTurf OS",
  appleWebApp: {
    capable: true,
    title: "TexasTurf",
    // "default" keeps black status-bar text — the app is light-first.
    statusBarStyle: "default",
    startupImage: IPHONE_SPLASH,
  },
  // Next 16 emits the modern `mobile-web-app-capable`; keep the legacy Apple
  // tag too so pre-16.4 iPhones still launch standalone.
  other: { "apple-mobile-web-app-capable": "yes" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bricolage.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-canvas text-ink">
        {children}
      </body>
    </html>
  );
}
